// 15 curated locations across Telangana
// This data will be used to seed Supabase AND as fallback when Supabase is not configured

const locations = [
  {
    id: '1',
    name: 'Charminar',
    slug: 'charminar',
    description: 'Charminar, meaning "Four Minarets", is a monument and mosque located in Hyderabad, Telangana. The landmark has become a global icon of Hyderabad, listed among the most recognized structures of India. It was built in 1591 CE by Muhammad Quli Qutb Shah, the fifth ruler of the Qutb Shahi dynasty. The structure is a masterpiece of Indo-Islamic architecture, standing at the intersection of the historical trade route linking the markets of Golconda with the port city of Machilipatnam. The four grand arches open into four streets, and at each corner stands a minaret rising to a height of 48.7 meters. The upper floor was used as a mosque and the roof once served as a court of justice.',
    short_description: 'Iconic 16th-century monument and mosque — the heart of Hyderabad\'s old city.',
    category: 'heritage',
    genre: ['historical', 'architectural', 'cultural'],
    group_type: ['solo', 'friends', 'family', 'couple'],
    latitude: 17.3616,
    longitude: 78.4747,
    district: 'Hyderabad',
    image_url: '/images/charminar.jpg',
    gallery: ['/images/charminar.jpg'],
    rating: 4.5,
    review_count: 328,
    is_featured: true,
    best_time: 'October to March (pleasant weather)',
    entry_fee: '₹25 for Indians, ₹300 for foreigners',
    nearby_transport: 'Charminar Bus Stop (0.1 km), Nampally Railway Station (3 km), MGBS Bus Station (2 km)',
    tags: ['Instagram Worthy', 'Night Life', 'Street Food'],
  },
  {
    id: '2',
    name: 'Golconda Fort',
    slug: 'golconda-fort',
    description: 'Golconda Fort is a fortified citadel and an early capital city of the Qutb Shahi dynasty, situated about 11 kilometers west of Hyderabad. The fort was originally built of mud by the Kakatiya dynasty as part of their western defenses along the lines of the Kondapalli Fort. The fort was rebuilt by Rani Rudrama Devi and her successor Prataparudra. The fort is renowned for its acoustic engineering — a handclap at the entrance gate can be heard at the top of the citadel, nearly a kilometer away. The fort also houses the famous Fateh Rahben gun and several royal palaces, halls, and temples.',
    short_description: 'A magnificent medieval fortress known for its acoustic marvels and diamond legacy.',
    category: 'heritage',
    genre: ['historical', 'architectural', 'adventure'],
    group_type: ['solo', 'friends', 'family'],
    latitude: 17.3833,
    longitude: 78.4011,
    district: 'Hyderabad',
    image_url: '/images/golconda.jpg',
    gallery: ['/images/golconda.jpg'],
    rating: 4.6,
    review_count: 256,
    is_featured: true,
    best_time: 'November to February, Light & Sound Show in evenings',
    entry_fee: '₹15 for Indians, ₹200 for foreigners. Light show ₹130',
    nearby_transport: 'Golconda Bus Stop (0.5 km), Lingampally Railway Station (8 km)',
    tags: ['Trekking', 'Sunset Spot', 'Photography'],
  },
  {
    id: '3',
    name: 'Ramoji Film City',
    slug: 'ramoji-film-city',
    description: 'Ramoji Film City is an integrated film studio complex situated in Hyderabad. It is one of the largest film studio complexes in the world, spreading across 1,666 acres. Established by Ramoji Rao, it has been certified by the Guinness World Records as the largest studio complex. The facility offers guided tours through various film sets, gardens, adventure zones, and entertainment shows. Visitors can explore replicas of famous locations, enjoy amusement rides, interactive shows, and live performances. The film city also houses permanent studio sets for various movie genres including war scenes, airport scenes, and palace halls.',
    short_description: 'World\'s largest film studio complex — a theme park meets Bollywood magic.',
    category: 'entertainment',
    genre: ['entertainment', 'adventure', 'family-fun'],
    group_type: ['friends', 'family', 'couple'],
    latitude: 17.2543,
    longitude: 78.6808,
    district: 'Hyderabad',
    image_url: '/images/ramoji.jpg',
    gallery: ['/images/ramoji.jpg'],
    rating: 4.3,
    review_count: 412,
    is_featured: true,
    best_time: 'Year-round, weekdays are less crowded',
    entry_fee: '₹1,500 onwards (includes guided tour and meals)',
    nearby_transport: 'Private buses from Hyderabad, 30 km from city center',
    tags: ['Family Friendly', 'Full Day Outing', 'Adventure'],
  },
  {
    id: '4',
    name: 'Hussain Sagar Lake',
    slug: 'hussain-sagar-lake',
    description: 'Hussain Sagar is a heart-shaped lake in Hyderabad, built by Ibrahim Quli Qutb Shah in 1563. The lake is fed by the River Musi and was originally intended for irrigation. In the center of the lake stands a large monolithic statue of Gautama Buddha, erected in 1992, weighing 350 tonnes and standing 18 meters tall. The lake is surrounded by Lumbini Park, NTR Gardens, and Sanjeevaiah Park, offering boat rides, a musical fountain, and evening laser shows. The Necklace Road along the lake is a popular evening hangout with food stalls, parks, and cycling tracks that light up beautifully at night.',
    short_description: 'Heart-shaped lake with a towering Buddha statue and vibrant Necklace Road.',
    category: 'lake',
    genre: ['scenic', 'romantic', 'recreation'],
    group_type: ['solo', 'friends', 'family', 'couple'],
    latitude: 17.4239,
    longitude: 78.4738,
    district: 'Hyderabad',
    image_url: '/images/hussain-sagar.jpg',
    gallery: ['/images/hussain-sagar.jpg'],
    rating: 4.2,
    review_count: 198,
    is_featured: true,
    best_time: 'Evenings for boat rides and lakeside walks',
    entry_fee: 'Free (boating charges extra: ₹75–₹300)',
    nearby_transport: 'Lakdi-ka-pul MMTS (1 km), Tank Bund Bus Stop (0.2 km)',
    tags: ['Sunset Spot', 'Boating', 'Night Life'],
  },
  {
    id: '5',
    name: 'Warangal Fort',
    slug: 'warangal-fort',
    description: 'Warangal Fort was a mud fort originally constructed by the Kakatiya ruler Ganapati Deva in the 13th century and later developed by his daughter, Queen Rudramadevi. The fort was built with three concentric fortification walls — an outer earthen wall, a stone wall, and an inner thorn-brush wall. The iconic four ornamental gateway arches (Kakatiya Kala Thoranam) at the entrance are remarkable examples of Kakatiya architecture, recognized as the emblem of the Kakatiya Heritage. The ruins include the Swayambhu temple, several Shiva temples, and elaborately carved pillars and gateways that showcase the artistic brilliance of the era.',
    short_description: 'Ancient Kakatiya dynasty fortress with iconic ornamental gateway arches.',
    category: 'heritage',
    genre: ['historical', 'architectural', 'cultural'],
    group_type: ['solo', 'friends', 'family'],
    latitude: 17.9551,
    longitude: 79.6036,
    district: 'Warangal',
    image_url: '/images/warangal-fort.jpg',
    gallery: ['/images/warangal-fort.jpg'],
    rating: 4.4,
    review_count: 142,
    is_featured: false,
    best_time: 'October to March',
    entry_fee: '₹15 for Indians, ₹200 for foreigners',
    nearby_transport: 'Warangal Railway Station (2 km), Warangal Bus Station (3 km)',
    tags: ['Historical', 'Photography', 'UNESCO Tentative'],
  },
  {
    id: '6',
    name: 'Thousand Pillar Temple',
    slug: 'thousand-pillar-temple',
    description: 'The Thousand Pillar Temple, also known as Rudreshwara Swamy Temple, is located in Hanamkonda, Warangal. Built in 1163 CE during the Kakatiya dynasty by King Rudra Deva, the temple is dedicated to three deities: Shiva, Vishnu, and Surya. The temple is a star-shaped structure, an architectural marvel of the Kakatiya period. The temple features intricately carved pillars (actually around 300, not literally 1000), with detailed sculptures of dancers, musicians, and mythological figures. The Nandi (bull) statue at the entrance is carved from a single black basalt stone and is considered one of the finest Nandi sculptures in South India.',
    short_description: 'A star-shaped Kakatiya temple with exquisite carvings from the 12th century.',
    category: 'temple',
    genre: ['spiritual', 'historical', 'architectural'],
    group_type: ['solo', 'family', 'couple'],
    latitude: 17.9193,
    longitude: 79.5615,
    district: 'Warangal',
    image_url: '/images/thousand-pillar.jpg',
    gallery: ['/images/thousand-pillar.jpg'],
    rating: 4.5,
    review_count: 167,
    is_featured: false,
    best_time: 'Year-round, early mornings for peaceful visits',
    entry_fee: 'Free',
    nearby_transport: 'Hanamkonda Bus Station (1 km), Kazipet Railway Station (5 km)',
    tags: ['Spiritual', 'Architecture', 'Photography'],
  },
  {
    id: '7',
    name: 'Nagarjuna Sagar Dam',
    slug: 'nagarjuna-sagar-dam',
    description: 'Nagarjuna Sagar Dam is one of the world\'s largest masonry dams, built across the Krishna River in Nalgonda district. Completed in 1967, the dam stands 124 meters high and 1.6 km long. Named after the Buddhist scholar Acharya Nagarjuna, the dam was built as part of a major irrigation and hydroelectric project. The Nagarjuna Sagar reservoir (Nagarjuna Sagar Lake) is one of the largest in India, and nearby sits the Nagarjunakonda island museum, accessible by boat, housing Buddhist relics and artifacts from the 3rd century. The dam gates opening during monsoon season is a spectacular sight, attracting thousands of visitors.',
    short_description: 'One of the world\'s largest masonry dams with Buddhist island museum nearby.',
    category: 'nature',
    genre: ['scenic', 'historical', 'adventure'],
    group_type: ['friends', 'family'],
    latitude: 16.5750,
    longitude: 79.3125,
    district: 'Nalgonda',
    image_url: 'https://images.unsplash.com/photo-1568849676085-51415703900f?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1568849676085-51415703900f?w=800&h=500&fit=crop'],
    rating: 4.3,
    review_count: 89,
    is_featured: false,
    best_time: 'August to December (dam gates open during monsoons)',
    entry_fee: '₹10 for dam, boat to island ₹100–₹300',
    nearby_transport: 'Macherla Railway Station (22 km), APSRTC buses from Hyderabad (150 km)',
    tags: ['Scenic', 'Weekend Getaway', 'Boating'],
  },
  {
    id: '8',
    name: 'Pochampally Village',
    slug: 'pochampally-village',
    description: 'Pochampally, also known as Bhoodan Pochampally, is a village in Yadadri Bhuvanagiri district of Telangana, famous worldwide for its unique handloom sarees with geometric patterns. Designated as one of UNESCO\'s "Creative City" projects, Pochampally ikat textiles are known for their distinctive dyeing technique where yarns are tie-dyed before weaving. Visitors can explore the weaving process firsthand, visit looms in small workshops, and purchase authentic Pochampally sarees directly from the weavers. The village has been transformed into a tourism spot with heritage walks, handloom museums, and live demonstrations of the traditional ikat weaving process.',
    short_description: 'UNESCO-recognized weaving village — birthplace of iconic Pochampally Ikat sarees.',
    category: 'culture',
    genre: ['cultural', 'shopping', 'heritage'],
    group_type: ['solo', 'friends', 'family', 'couple'],
    latitude: 17.3500,
    longitude: 78.8167,
    district: 'Yadadri',
    image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&h=500&fit=crop'],
    rating: 4.1,
    review_count: 76,
    is_featured: false,
    best_time: 'Year-round, weekdays are best to see weavers at work',
    entry_fee: 'Free',
    nearby_transport: 'Bhongir Railway Station (15 km), TSRTC buses from Hyderabad (50 km)',
    tags: ['Cultural', 'Shopping', 'Handloom'],
  },
  {
    id: '9',
    name: 'Ananthagiri Hills',
    slug: 'ananthagiri-hills',
    description: 'Ananthagiri Hills is a hill station and forest area located in Vikarabad district, about 80 km from Hyderabad. The hills rise to an elevation of 2,848 feet above sea level and are part of the Eastern Ghats. The region is covered with dense deciduous forests, coffee plantations, and is a popular trekking destination. The Ananthagiri Temple, dedicated to Lord Shiva, sits atop one of the hills and is believed to be the origin of the River Musi. The area features several trekking trails of varying difficulty, natural swimming spots, small waterfalls during monsoons, and eco-resort accommodations surrounded by pristine forest.',
    short_description: 'Lush hill station with trekking trails, coffee plantations, and misty forests.',
    category: 'nature',
    genre: ['nature', 'adventure', 'trekking'],
    group_type: ['solo', 'friends', 'couple'],
    latitude: 17.2333,
    longitude: 78.1167,
    district: 'Vikarabad',
    image_url: 'https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1501785888041-af3ef285b470?w=800&h=500&fit=crop'],
    rating: 4.4,
    review_count: 203,
    is_featured: true,
    best_time: 'July to November (monsoon greenery), November–February (cool weather)',
    entry_fee: 'Free (eco-tourism activities have separate charges)',
    nearby_transport: 'Vikarabad Railway Station (8 km), private transport from Hyderabad',
    tags: ['Trekking', 'Nature', 'Weekend Getaway'],
  },
  {
    id: '10',
    name: 'Papikondalu',
    slug: 'papikondalu',
    description: 'Papikondalu (Papi Hills) is a range of hills along the River Godavari in Khammam district and surrounding areas. The hills form a spectacular gorge through which the Godavari River flows, creating one of the most breathtaking river cruise routes in India. The multi-hour boat cruise from Bhadrachalam to Papikondalu passes through dense forests, tribal villages, and narrow gorges where the hills seem to close in from both sides. The area is home to the Koya and Gond tribal communities and features lush vegetation, rare bird species, and a serene natural beauty that makes it one of Telangana\'s most unique experiences.',
    short_description: 'Stunning river gorge on the Godavari — cruise through dramatic hills and tribal villages.',
    category: 'nature',
    genre: ['nature', 'scenic', 'adventure'],
    group_type: ['friends', 'family', 'couple'],
    latitude: 17.4500,
    longitude: 81.1000,
    district: 'Khammam',
    image_url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&h=500&fit=crop'],
    rating: 4.7,
    review_count: 118,
    is_featured: false,
    best_time: 'September to March (post-monsoon, river is full)',
    entry_fee: 'Boat cruise ₹2,000–₹5,000 depending on type',
    nearby_transport: 'Bhadrachalam (starting point), private buses from Hyderabad (310 km)',
    tags: ['River Cruise', 'Nature', 'Adventure'],
  },
  {
    id: '11',
    name: 'Bhongir Fort',
    slug: 'bhongir-fort',
    description: 'Bhongir Fort is a hilltop fort built on a monolithic rock, located in Yadadri Bhuvanagiri district. Originally named Tribhuvanagiri, the fort was constructed in the 10th century CE by the Chalukya ruler Tribhuvanamalla Vikramaditya VI. The fort sits on a massive egg-shaped granite rock that rises 500 feet from the surrounding plain, making it visible for kilometers. The trek to the top is challenging but rewarding, with steep steps carved into the rock, narrow passages, and a cannon platform at the summit offering panoramic 360-degree views. The fort changed hands between the Kakatiyas, Bahmani Sultanate, and Qutb Shahis.',
    short_description: 'Thrilling hilltop fort on a monolithic rock — 360° views from the ancient summit.',
    category: 'heritage',
    genre: ['historical', 'adventure', 'trekking'],
    group_type: ['solo', 'friends'],
    latitude: 17.5167,
    longitude: 78.8833,
    district: 'Yadadri',
    image_url: 'https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1585409677983-0f6c41ca9c3b?w=800&h=500&fit=crop'],
    rating: 4.3,
    review_count: 154,
    is_featured: false,
    best_time: 'October to February (avoid summers, rock gets very hot)',
    entry_fee: '₹10',
    nearby_transport: 'Bhongir Railway Station (1 km), frequent trains from Hyderabad (50 km)',
    tags: ['Trekking', 'Adventure', 'Sunrise Spot'],
  },
  {
    id: '12',
    name: 'Medak Cathedral',
    slug: 'medak-cathedral',
    description: 'Medak Cathedral, officially known as the Cathedral Church of the Medak Diocese, is one of the largest churches in Asia, located in Medak town. Built between 1914 and 1924, the cathedral was designed by Reverend Charles Walker Posnett. The church features stunning stained-glass windows, the largest in Asia, imported from Europe. The Gothic-style architecture with its towering spire, vaulted ceilings, and massive prayer hall can accommodate up to 5,000 worshippers. The cathedral complex also includes a beautiful garden, a graveyard with colonial-era graves, and an old bell tower. During Christmas, the cathedral hosts spectacular celebrations that attract visitors from across India.',
    short_description: 'One of Asia\'s largest cathedrals with stunning European stained-glass windows.',
    category: 'heritage',
    genre: ['spiritual', 'architectural', 'historical'],
    group_type: ['solo', 'family', 'couple'],
    latitude: 18.0444,
    longitude: 78.2639,
    district: 'Medak',
    image_url: 'https://images.unsplash.com/photo-1548625361-1adcd1e1c777?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1548625361-1adcd1e1c777?w=800&h=500&fit=crop'],
    rating: 4.5,
    review_count: 96,
    is_featured: false,
    best_time: 'Year-round, Christmas for special celebrations',
    entry_fee: 'Free',
    nearby_transport: 'Medak Bus Station (0.5 km), nearest railway station Secunderabad (100 km)',
    tags: ['Spiritual', 'Architecture', 'Christmas Special'],
  },
  {
    id: '13',
    name: 'Laknavaram Lake',
    slug: 'laknavaram-lake',
    description: 'Laknavaram Lake is a beautiful freshwater lake located in the dense forests of Mulugu district (formerly Warangal district). The lake is set amidst two hills covered with thick deciduous forest and is accessed via a unique hanging bridge — a swinging bamboo and cable bridge that stretches across the lake, creating a memorable adventure. Built during the Kakatiya period, the lake was originally an irrigation tank. The surrounding forest is rich in wildlife and bird species. Boating on the calm, mirror-like waters with the forest canopy reflected perfectly is an unforgettable experience. Tribal villages nearby offer a glimpse into indigenous Koya culture.',
    short_description: 'Forest lake with a thrilling hanging bridge — hidden gem in Telangana\'s tribal belt.',
    category: 'nature',
    genre: ['nature', 'adventure', 'scenic'],
    group_type: ['friends', 'couple'],
    latitude: 18.0167,
    longitude: 80.1667,
    district: 'Warangal',
    image_url: 'https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1439066615861-d1af74d74000?w=800&h=500&fit=crop'],
    rating: 4.6,
    review_count: 87,
    is_featured: false,
    best_time: 'August to January (post-monsoon, lake is full)',
    entry_fee: '₹20, Boating ₹100–₹200',
    nearby_transport: 'Warangal (80 km), private transport recommended',
    tags: ['Hidden Gem', 'Boating', 'Nature'],
  },
  {
    id: '14',
    name: 'Kuntala Waterfall',
    slug: 'kuntala-waterfall',
    description: 'Kuntala Waterfall is the highest waterfall in Telangana, with a total drop of about 200 feet (61 meters) in two tiers. Located in Adilabad district near the village of Kuntala, the waterfall is formed on the Kadam River. The falls are surrounded by dense Sahyadri forest and are most spectacular during and just after the monsoon season (July–October) when the river is in full flow. A trek through the forest leads to the base of the falls, where visitors can enjoy the cool spray and natural pool. The area is part of the Kawal Wildlife Sanctuary, home to tigers, leopards, and various bird species.',
    short_description: 'Telangana\'s highest waterfall — a 200-foot cascade through pristine Sahyadri forest.',
    category: 'nature',
    genre: ['nature', 'adventure', 'trekking'],
    group_type: ['friends', 'couple'],
    latitude: 19.5167,
    longitude: 78.6167,
    district: 'Adilabad',
    image_url: 'https://images.unsplash.com/photo-1432405972618-c6b0cfba1b3e?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1432405972618-c6b0cfba1b3e?w=800&h=500&fit=crop'],
    rating: 4.4,
    review_count: 73,
    is_featured: false,
    best_time: 'July to October (monsoon — waterfall at full glory)',
    entry_fee: '₹30',
    nearby_transport: 'Nirmal (40 km), Adilabad (50 km), buses from Hyderabad (290 km)',
    tags: ['Waterfall', 'Trekking', 'Monsoon Special'],
  },
  {
    id: '15',
    name: 'Shamirpet Deer Park',
    slug: 'shamirpet-deer-park',
    description: 'Shamirpet Deer Park is a protected wildlife area located about 25 km north of Hyderabad in Medchal-Malkajgiri district. Spread across 30 acres, the park is home to hundreds of spotted deer (chital), blackbuck, and various bird species including peacocks. The park is set beside the scenic Shamirpet Lake, providing a picturesque backdrop for wildlife watching. A designated walking trail winds through the park, and visitors can observe deer herds grazing freely in their natural habitat. The adjacent lake area is popular for fishing (with permits), birdwatching, and picnicking, making it an ideal half-day escape from the city.',
    short_description: 'Serene deer sanctuary beside a lake — a quick nature escape from Hyderabad.',
    category: 'nature',
    genre: ['nature', 'wildlife', 'scenic'],
    group_type: ['solo', 'family', 'couple'],
    latitude: 17.5833,
    longitude: 78.5500,
    district: 'Medchal',
    image_url: 'https://images.unsplash.com/photo-1474511320723-9a56873571b7?w=800&h=500&fit=crop',
    gallery: ['https://images.unsplash.com/photo-1474511320723-9a56873571b7?w=800&h=500&fit=crop'],
    rating: 4.0,
    review_count: 132,
    is_featured: false,
    best_time: 'October to February (cool weather, deer are more active)',
    entry_fee: '₹20 adults, ₹10 children',
    nearby_transport: 'TSRTC buses from Secunderabad (25 km), private transport',
    tags: ['Family Friendly', 'Wildlife', 'Half-Day Trip'],
  },
];

// Category metadata
export const categories = [
  { id: 'all', label: 'All Places', icon: 'Globe' },
  { id: 'heritage', label: 'Heritage', icon: 'Castle' },
  { id: 'nature', label: 'Nature', icon: 'TreePine' },
  { id: 'temple', label: 'Temples', icon: 'Landmark' },
  { id: 'lake', label: 'Lakes', icon: 'Waves' },
  { id: 'entertainment', label: 'Entertainment', icon: 'Clapperboard' },
  { id: 'culture', label: 'Culture', icon: 'Palette' },
];

export const groupTypes = [
  { id: 'all', label: 'Any Group', icon: 'Users' },
  { id: 'solo', label: 'Solo', icon: 'User' },
  { id: 'friends', label: 'Friends', icon: 'Users' },
  { id: 'family', label: 'Family', icon: 'Home' },
  { id: 'couple', label: 'Couple', icon: 'Heart' },
];

export default locations;
